# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87c1cae9a53d24ab08a9ae48e0dba0a0ca514e51d8d4bdf6528060aa421a5e306b639f0b3a9e8eb999a2c6a3a4bad38ed9bfaecb7a2041f1bd7e86b8f6af6dde

test:
  secret_key_base: 6cf2746c74996d8ec8852e715169f3524bdbc9908c5dfb05d6efd64cbb977c5116281b8fc8618643ef1b7dbe9e72a54ed80756d343d02bdceff4f6aae30a14cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
